server:
  port: 8081

spring:
  #  application:
  #    name: oauth2-server-rbac
  ## 数据库配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2_demo?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  ## 覆盖重复bean配置
  main:
    allow-bean-definition-overriding: true
  ## Redis 配置
  redis:
    host: 192.168.18.195
    port: 32268
    password: itszhongxin
  mvc:
    locale: zh_CN

## mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      table-underline: true
      db-type: mysql
      logic-delete-field: isDelete  #全局逻辑删除字段。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    map-underscore-to-camel-case: true #开启驼峰
    cache-enabled: false
    call-setters-on-nulls: true # 为null字段也返回
    jdbc-type-for-null: null
  mapper-locations: classpath*:mapper/*Mapper.xml

## 日志配置
logging:
  level:
    org:
      springframework:
        security:
          oauth2: DEBUG
    com:
      zjy:
        oauth2server:
          mapper: debug
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%t]){faint} %clr(%-40.40logger{39}){cyan}[%clr(%line)]    %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
#    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39}[lineno:%line]: %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

## security 配置
zjy:
  security:
    oauth2:
      type: redis
#    client:
#      # 客户端 id
#      resourceId: product